import prisma from "../db.server";
import { calculatePaymentStatus } from "./order-status-helpers";

/**
 * v2 data model sync: the app database is authoritative for app-managed
 * state; Shopify is authoritative only for what Shopify truly owns.
 *
 * - First sight of an order: everything is taken from Shopify/metafields
 *   (bootstrap of legacy data).
 * - After that, sync refreshes Shopify-owned fields (name, payment status,
 *   customer, note, line-item titles/quantities/positions) but never
 *   overwrites app-managed state the DB already has (contact status,
 *   overall status, item statuses/attributes, notification log). This is
 *   what stops a position-shifted metafield from corrupting correct rows.
 * - Sync must never break a page load — callers use syncInBackground.
 */

function metafieldMap(metafields) {
  const map = new Map();
  for (const edge of metafields?.edges || []) {
    if (edge?.node?.key != null) {
      map.set(edge.node.key, edge.node.value);
    }
  }
  return map;
}

function parseJsonArray(value) {
  if (!value) return null;
  try {
    const parsed = JSON.parse(value);
    return Array.isArray(parsed) ? parsed : null;
  } catch {
    return null;
  }
}

/**
 * Build DB rows from a GraphQL Order/DraftOrder node as fetched by the
 * admin loaders (metafields + lineItems connections).
 *
 * @param {object} node GraphQL node with at least id, name; optionally
 *   metafields, lineItems, customer, createdAt, note/note2.
 * @param {"ORDER" | "DRAFT_ORDER"} kind
 */
export function buildSpecialOrderRecord(node, kind) {
  const mf = metafieldMap(node.metafields);

  const lineItemNodes = (node.lineItems?.edges || []).map((e) => e.node);
  const items = lineItemNodes.map((li, index) => {
    const position = index + 1;
    const attributes =
      parseJsonArray(mf.get(`lineitem_${position}_attributes`)) ??
      (Array.isArray(li.customAttributes) && li.customAttributes.length
        ? li.customAttributes.map(({ key, value }) => ({ key, value }))
        : null);

    return {
      shopifyLineItemId: li.id ?? null,
      position,
      title: li.title ?? "Item",
      variantTitle: li.variantTitle ?? li.variant?.title ?? null,
      quantity: li.quantity ?? 1,
      status: mf.get(`product_${position}_order_status`) ?? null,
      attributes,
      adjustmentType: mf.get(`product_${position}_adjustment_type`) ?? null,
      exchangedForTitle:
        mf.get(`product_${position}_exchanged_for_title`) ?? null,
    };
  });

  const notifications = (parseJsonArray(mf.get("pickup_notification_log")) || [])
    .filter((entry) => entry && entry.sentAt && entry.recipientEmail)
    .map((entry) => ({
      type: entry.type || "email_ready_pickup",
      recipientEmail: entry.recipientEmail,
      employeeNote: entry.employeeNote || null,
      sentAt: new Date(entry.sentAt),
    }))
    .filter((entry) => !Number.isNaN(entry.sentAt.getTime()));

  return {
    order: {
      shopifyId: node.id,
      kind,
      name: node.name ?? "",
      contactStatus: mf.get("contact_status") ?? null,
      overallStatus: mf.get("overall_order_status") ?? null,
      paymentStatus: calculatePaymentStatus(node),
      shopifyStatus: kind === "DRAFT_ORDER" ? (node.status ?? null) : null,
      note: node.note ?? node.note2 ?? null,
      customerShopifyId: node.customer?.id ?? null,
      customerName: node.customer?.displayName ?? null,
      customerEmail: node.customer?.email ?? null,
      customerPhone: node.customer?.phone ?? null,
      shopifyCreatedAt: node.createdAt ? new Date(node.createdAt) : null,
    },
    items,
    notifications,
  };
}

function hasValue(v) {
  if (v == null) return false;
  if (typeof v === "string") return v.trim() !== "";
  if (Array.isArray(v)) return v.length > 0;
  return true;
}

/**
 * Pair incoming Shopify line items with existing DB rows: stable GIDs
 * first, then position for the leftovers (draft line-item GIDs are
 * regenerated by Shopify on every draft update, so position is the only
 * link across a draft edit).
 *
 * @returns {Array<{ incoming: object, existing: object | null }>}
 */
function matchItems(incomingItems, existingItems) {
  const unmatched = new Set(existingItems);
  const byGid = new Map();
  for (const item of existingItems) {
    if (item.shopifyLineItemId) byGid.set(item.shopifyLineItemId, item);
  }

  const pairs = incomingItems.map((incoming) => {
    const existing = incoming.shopifyLineItemId
      ? byGid.get(incoming.shopifyLineItemId)
      : null;
    if (existing && unmatched.has(existing)) {
      unmatched.delete(existing);
      return { incoming, existing };
    }
    return { incoming, existing: null };
  });

  const leftoverByPosition = new Map(
    [...unmatched].map((item) => [item.position, item])
  );
  for (const pair of pairs) {
    if (pair.existing) continue;
    const candidate = leftoverByPosition.get(pair.incoming.position);
    if (candidate) {
      pair.existing = candidate;
      leftoverByPosition.delete(pair.incoming.position);
      unmatched.delete(candidate);
    }
  }

  return pairs;
}

/**
 * Pure item merge: Shopify-owned fields from the incoming node, app-managed
 * fields from the DB row when the DB already has them. Exported for tests.
 */
export function mergeItems(incomingItems, existingItems) {
  return matchItems(incomingItems, existingItems).map(
    ({ incoming, existing: prev }) => ({
      shopifyLineItemId:
        incoming.shopifyLineItemId ?? prev?.shopifyLineItemId ?? null,
      position: incoming.position,
      title: incoming.title,
      variantTitle: incoming.variantTitle,
      quantity: incoming.quantity,
      status: hasValue(prev?.status) ? prev.status : incoming.status,
      attributes: hasValue(prev?.attributes)
        ? prev.attributes
        : incoming.attributes,
      adjustmentType: hasValue(prev?.adjustmentType)
        ? prev.adjustmentType
        : incoming.adjustmentType,
      exchangedForTitle: hasValue(prev?.exchangedForTitle)
        ? prev.exchangedForTitle
        : incoming.exchangedForTitle,
    })
  );
}

/**
 * Upsert one special order (header + items + notifications) into the DB.
 *
 * DB-authoritative merge: Shopify-owned fields always refresh; app-managed
 * fields (statuses, item attributes, notifications) are only taken from
 * Shopify when the DB doesn't have them yet, so stale or position-shifted
 * metafields can never overwrite state written through the app.
 *
 * @param {string} shop myshopify domain
 * @param {object} node GraphQL Order/DraftOrder node
 * @param {"ORDER" | "DRAFT_ORDER"} kind
 * @param {{ convertedFromDraftId?: string }} [extra]
 */
export async function syncSpecialOrder(shop, node, kind, extra = {}) {
  if (!node?.id) return null;
  const { order, items, notifications } = buildSpecialOrderRecord(node, kind);

  return prisma.$transaction(async (tx) => {
    const existing = await tx.specialOrder.findUnique({
      where: { shop_shopifyId: { shop, shopifyId: order.shopifyId } },
      include: { items: true, notifications: true },
    });

    let record;
    if (!existing) {
      // First sight: bootstrap everything from Shopify/metafields.
      record = await tx.specialOrder.create({
        data: {
          shop,
          ...order,
          convertedFromDraftId: extra.convertedFromDraftId ?? null,
        },
      });
    } else {
      record = await tx.specialOrder.update({
        where: { id: existing.id },
        data: {
          // Shopify-owned header fields.
          kind: order.kind,
          name: order.name,
          paymentStatus: order.paymentStatus,
          shopifyStatus: order.shopifyStatus,
          note: order.note,
          customerShopifyId: order.customerShopifyId,
          customerName: order.customerName,
          customerEmail: order.customerEmail,
          customerPhone: order.customerPhone,
          shopifyCreatedAt: order.shopifyCreatedAt,
          // App-managed: DB wins once set.
          contactStatus: hasValue(existing.contactStatus)
            ? existing.contactStatus
            : order.contactStatus,
          overallStatus: hasValue(existing.overallStatus)
            ? existing.overallStatus
            : order.overallStatus,
          ...(extra.convertedFromDraftId
            ? { convertedFromDraftId: extra.convertedFromDraftId }
            : {}),
          syncedAt: new Date(),
        },
      });
    }

    // Merge items in memory, then replace the rows in one shot (in-place
    // position updates would trip the (specialOrderId, position) unique
    // constraint when items shift).
    const mergedItems = mergeItems(items, existing?.items ?? []);

    await tx.specialOrderItem.deleteMany({
      where: { specialOrderId: record.id },
    });
    if (mergedItems.length) {
      await tx.specialOrderItem.createMany({
        data: mergedItems.map((item) => ({
          ...item,
          specialOrderId: record.id,
        })),
      });
    }

    // Notifications are append-only: add metafield entries the DB doesn't
    // have yet, never delete DB entries (dbAppendNotification may have
    // rows the metafield log is missing).
    const seen = new Set(
      (existing?.notifications ?? []).map(
        (n) => `${n.type}|${n.recipientEmail}|${n.sentAt.getTime()}`
      )
    );
    const newNotifications = notifications.filter(
      (n) => !seen.has(`${n.type}|${n.recipientEmail}|${n.sentAt.getTime()}`)
    );
    if (newNotifications.length) {
      await tx.notificationLog.createMany({
        data: newNotifications.map((n) => ({
          ...n,
          specialOrderId: record.id,
        })),
      });
    }

    return record;
  });
}

const ORDER_FOR_SYNC = `#graphql
  query OrderForDbSync($id: ID!) {
    order(id: $id) {
      id
      name
      createdAt
      note
      displayFinancialStatus
      totalPriceSet { shopMoney { amount currencyCode } }
      totalRefundedSet { shopMoney { amount currencyCode } }
      totalOutstandingSet { shopMoney { amount currencyCode } }
      customer {
        id
        displayName
        email
        phone
      }
      metafields(first: 250, namespace: "custom") {
        edges { node { key value } }
      }
      lineItems(first: 50) {
        edges {
          node {
            id
            title
            quantity
            variantTitle
            customAttributes { key value }
          }
        }
      }
    }
  }
`;

const DRAFT_FOR_SYNC = `#graphql
  query DraftOrderForDbSync($id: ID!) {
    draftOrder(id: $id) {
      id
      name
      status
      createdAt
      note2
      customer {
        id
        displayName
        email
        phone
      }
      metafields(first: 250, namespace: "custom") {
        edges { node { key value } }
      }
      lineItems(first: 50) {
        edges {
          node {
            id
            title
            quantity
            variant { title }
            customAttributes { key value }
          }
        }
      }
    }
  }
`;

/**
 * Fetch one Order/DraftOrder from Shopify by GID and mirror it into the DB.
 * Used by the orders/create webhook and the POS sync-ping endpoint.
 *
 * @param {Function} graphql admin GraphQL client
 * @param {string} shop myshopify domain
 * @param {string} gid Order or DraftOrder GID
 * @param {{ convertedFromDraftId?: string }} [extra]
 */
export async function fetchAndSyncSpecialOrderById(graphql, shop, gid, extra) {
  const isDraft = String(gid).includes("DraftOrder");
  const res = await graphql(isDraft ? DRAFT_FOR_SYNC : ORDER_FOR_SYNC, {
    variables: { id: gid },
  });
  const json = await res.json();
  const node = isDraft ? json.data?.draftOrder : json.data?.order;
  if (!node) return null;
  return syncSpecialOrder(
    shop,
    node,
    isDraft ? "DRAFT_ORDER" : "ORDER",
    extra
  );
}

/**
 * Fire-and-forget wrapper: page loads must never fail or slow down
 * because the shadow sync had a problem.
 */
export function syncInBackground(shop, node, kind, extra) {
  syncSpecialOrder(shop, node, kind, extra).catch((e) => {
    console.error(
      `[special-order-sync] failed for ${node?.id ?? "unknown"}:`,
      e instanceof Error ? e.message : e
    );
  });
}
